curl --http2 --request GET --url https://www.tokenville.fun/api/markets/5/winners \
    --header 'content-type: application/json' \
    --header 'X-KEY: 7510744d-4e40-4fae-9207-d9efbd3d8f91' \
    --header 'X-SIGNATURE: 	c9rMqT93IaO5VyoNXCswCUo159v9NFrO' \
    --header 'X-TIMESTAMP: 12345678' \
    --data   '{
                
              }' 