curl --http2 --request POST --url https://www.tokenville.fun/api/deposit/3 \
    --header 'content-type: application/json' \
    --header 'X-SHADOW: 6' \
    --header 'X-DEVICE: 10' \
    --header 'X-SMARKT: 3' \
    --header 'X-User-Locale: de' \
    --data   '{
                
              }' 